apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: orders-reply
  namespace: kafka
  labels:
    strimzi.io/cluster: my-cluster
spec:
  topicName: orders.reply
  partitions: 1
  replicas: 1
